skip_train: false
skip_test: false
skip_mesh: true
skip_cull: true
skip_metrics: false
render_path: false
case_name: Caterpillar
root_dir: /home/salam4/3d_datasets/tnt/TNT_GOF/TrainingSet/${case_name}
pipeline:
  convert_SHs_python: false
  compute_view2gaussian_python: false
  debug: false
  depth_ratio: 0.1
  use_multi_normal: false
  checkpoint_iterations: []
  reciprocal_z: false
  occlusion_awared_denom: false
  unbounded: false
  num_cluster: 1
  mesh_res: 1024
  voxel_size: 0.004
  sdf_trunc: 0.016
  depth_trunc: 3.5
dataset:
  name: colmap
  model_path: ${model_path}
  type: all
  kernel_size: -1
  undistortion: true
  use_alpha: false
  downsample: 1
  ncc_scale: ${dataset.downsample}
  eval: true
  hold: 8
  resolution: -1
  data_device: cuda
  white_background: false
  multi_view_max_dis: 1.5
  multi_view_min_dis: 0.01
  multi_view_max_angle: 30
gs_model:
  sigma: 3.0
  sh_degree: 3
  root_dir: ${root_dir}
  output_dir: ${root_dir}/exp/QGS
  model_path: ${model_path}
  load_iteration: false
  images: images
  downsample: ${dataset.downsample}
  white_background: ${dataset.white_background}
  eval: ${dataset.eval}
  multi_view_num: 8
  use_app: false
optimizer:
  use_virtul_cam: false
  wo_image_weight: true
  exposure_compensation: false
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 1.6e-06
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.0005
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  normal_from_iter: 7000
  multi_view_weight_from_iter: 7000
  multi_view_weight_until_iter: 30000
  dist_from_iter: 3000
  curv_from_iter: 1000000
  densify_grad_threshold: 0.3
  random_background: false
  reset_opacity_densify_delay: 0
  multi_view_patch_size: 3
  multi_view_sample_num: 102400
  multi_view_pixel_noise_th: 1.0
  multi_view_ncc_weight: 0.5
  multi_view_geo_weight: 0.03
  wo_use_geo_occ_aware: false
  virtul_cam_prob: 0.5
  curvature_clamp_threshold: -5.0
  occupancy_rate: 0.0
  lambda_dssim: 0.2
  lambda_dist: 1000.0
  lambda_curv_dist: 0.0
  lambda_curv_flat: 0.0
  lambda_normal: 0.05
model_path: /home/salam4/trained_models/QGS_models/Caterpillar
defaults:
- ./base.yaml
GT_path: null
model_root: /home/salam4/trained_models/QGS_models/${case_name}
load_model_path: ${model_path}
dataset_GT_path: /home/zzy_group/data/public_data/TNT_GOF/GT/${case_name}
traj_path: ${root_dir}/${case_name}_COLMAP_SfM.log
mesh_ply_path: ${load_model_path}/train/ours_30000/fuse_post.ply
eval_output_path: ${load_model_path}/train/ours_30000
